export const testJson = [
  {
    "name": "证件照",
    "id": "",
    "hint": "必填",
    "required": true,
    "type": "title",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "添加头像",
    "id": "",
    "hint": "",
    "required": true,
    "type": "picture-upload",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "基本信息",
    "id": "",
    "hint": "必填",
    "required": false,
    "type": "title",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "姓名",
    "id": "1",
    "hint": "输入姓名",
    "required": true,
    "type": "text",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "50",
    "content": [],
    "template": []
  },
  {
    "name": "性别",
    "id": "",
    "hint": "",
    "required": true,
    "type": "radio",
    "optionNum": "2",
    "optionValue": [
      "男",
      "女"
    ],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "出生日期",
    "id": "1",
    "hint": "",
    "required": true,
    "type": "date",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "50",
    "content": [],
    "template": []
  },
  {
    "name": "国籍",
    "id": "1",
    "hint": "",
    "required": true,
    "type": "radio",
    "optionNum": "2",
    "optionValue": [
      "中国",
      "外国"
    ],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "籍贯",
    "id": "",
    "hint": "输入籍贯",
    "required": true,
    "type": "text",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "50",
    "content": [],
    "template": []
  },
  {
    "name": "身份证号或护照号",
    "id": "1",
    "hint": "输入身份证或护照",
    "required": true,
    "type": "text",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "50",
    "content": [],
    "template": []
  },
  {
    "name": "学术学历",
    "id": "",
    "hint": "必填",
    "required": false,
    "type": "title",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "专业",
    "id": "1",
    "hint": "输入专业",
    "required": true,
    "type": "text",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "50",
    "content": [],
    "template": []
  },
  {
    "name": "最高学位",
    "id": "",
    "hint": "输入最高学位",
    "required": true,
    "type": "text",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "50",
    "content": [],
    "template": []
  },
  {
    "name": "最高学历",
    "id": "",
    "hint": "",
    "required": true,
    "type": "radio",
    "optionNum": "2",
    "optionValue": [
      "硕士研究生",
      "博士研究生"
    ],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "人才称号",
    "id": "",
    "hint": "可多选",
    "required": true,
    "type": "checkbox",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "10",
    "optionMoreValue": [
      "无",
      "院士",
      "长江学者特聘教授",
      "国家千人计划入选者",
      "国家青年杰出人才基金获得者",
      "国家自然科学基金优秀青年基金项目获得者",
      "国家“千人计划”青年人才无",
      "“国家特支计划”青年拔尖人才无",
      "“长江学者奖励计划”青年学者",
      "其他人才称号"
    ],
    "childComps": [],
    "numberLimit": "",
    "content": [
      "“国家特支计划”青年拔尖人才无",
      "“长江学者奖励计划”青年学者",
      "其他人才称号"
    ],
    "template": []
  },
  {
    "name": "职务",
    "id": "",
    "hint": "",
    "required": true,
    "type": "radio",
    "optionNum": "4",
    "optionValue": [
      "院长",
      "副院长",
      "系主任",
      "其他"
    ],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "职称",
    "id": "",
    "hint": "",
    "required": true,
    "type": "radio",
    "optionNum": "13",
    "optionValue": [
      "教授",
      "副教授",
      "讲师",
      "助教",
      "研究员",
      "副研究员",
      "助理研究员",
      "研究实习员",
      "教授级高级工程师",
      "高级工程师",
      "工程师",
      "助理工程师",
      "其他"
    ],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "学科领域",
    "id": "",
    "hint": "输入学科领域",
    "required": true,
    "type": "text",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "50",
    "content": [],
    "template": []
  },
  {
    "name": "现工作单位",
    "id": "1",
    "hint": "输入现工作单位",
    "required": true,
    "type": "text",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "50",
    "content": [],
    "template": []
  },
  {
    "name": "博士后单位",
    "id": "",
    "hint": "",
    "required": true,
    "type": "radio",
    "optionNum": "3",
    "optionValue": [
      "无",
      "境内",
      "境外"
    ],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "联系方式",
    "id": "",
    "hint": "必填",
    "required": false,
    "type": "title",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "联系手机",
    "id": "1",
    "hint": "输入手机号",
    "required": true,
    "type": "number",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "11",
    "content": [],
    "template": []
  },
  {
    "name": "电子邮箱",
    "id": "1",
    "hint": "输入电子邮箱",
    "required": true,
    "type": "email",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "50",
    "content": [],
    "template": []
  },
  {
    "name": "通讯地址",
    "id": "1",
    "hint": "输入通讯地址",
    "required": true,
    "type": "text",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "100",
    "content": [],
    "template": []
  },
  {
    "name": "工作经历",
    "id": "",
    "hint": "必填",
    "required": false,
    "type": "title",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "第一学历院校",
    "id": "1",
    "hint": "输入第一学历院校",
    "required": true,
    "type": "text",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "100",
    "content": [],
    "template": []
  },
  {
    "name": "最高学历院校",
    "id": "1",
    "hint": "输入最高学历院校",
    "required": true,
    "type": "text",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "100",
    "content": [],
    "template": []
  },
  {
    "name": "",
    "id": "",
    "hint": "",
    "required": false,
    "type": "experience",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [
      [
        {
          "name": "开始日期",
          "id": "",
          "hint": "",
          "required": true,
          "type": "date",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "",
          "content": [],
          "template": []
        },
        {
          "name": "结束日期",
          "id": "",
          "hint": "",
          "required": true,
          "type": "date",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "",
          "content": [],
          "template": []
        },
        {
          "name": "单位",
          "id": "",
          "hint": "输入单位",
          "required": true,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "经历类型",
          "id": "",
          "hint": "",
          "required": true,
          "type": "radio",
          "optionNum": "3",
          "optionValue": [
            "学习",
            "工作",
            "博士后"
          ],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "",
          "content": [],
          "template": []
        }
      ]
    ],
    "numberLimit": "10",
    "content": [],
    "template": [
      [
        {
          "name": "开始日期",
          "id": "",
          "hint": "",
          "required": true,
          "type": "date",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "",
          "content": [],
          "template": []
        },
        {
          "name": "结束日期",
          "id": "",
          "hint": "",
          "required": true,
          "type": "date",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "",
          "content": [],
          "template": []
        },
        {
          "name": "单位",
          "id": "",
          "hint": "输入单位",
          "required": true,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "经历类型",
          "id": "",
          "hint": "",
          "required": true,
          "type": "radio",
          "optionNum": "3",
          "optionValue": [
            "学习",
            "工作",
            "博士后"
          ],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "",
          "content": [],
          "template": []
        }
      ],
      [
        {
          "name": "专业",
          "id": "",
          "hint": "输入专业",
          "required": true,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "学习层次",
          "id": "",
          "hint": "",
          "required": true,
          "type": "radio",
          "optionNum": "4",
          "optionValue": [
            "专科",
            "本科",
            "硕士",
            "博士"
          ],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "",
          "content": [],
          "template": []
        }
      ],
      [
        {
          "name": "职位",
          "id": "",
          "hint": "输入职位",
          "required": true,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        }
      ]
    ]
  },
  {
    "name": "论文著作",
    "id": "",
    "hint": "请填写本人第一作者或通讯作者，不超过十五篇",
    "required": false,
    "type": "title",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "",
    "id": "",
    "hint": "",
    "required": false,
    "type": "thesis-work",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [
      [
        {
          "name": "名称",
          "id": "",
          "hint": "输入名称",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "出版单位或刊物名称",
          "id": "",
          "hint": "输入单位或名称",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "期号",
          "id": "",
          "hint": "输入期号",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "起止页码",
          "id": "",
          "hint": "输入起止页码",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "出版或发布年度",
          "id": "",
          "hint": "输入出版或年度",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "被SCI或EI或SSCI或CSSCI收录",
          "id": "",
          "hint": "填写是否",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "期刊影响因子",
          "id": "",
          "hint": "输入影响因子",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "被ESI收录为热点论文情况",
          "id": "",
          "hint": "填写情况",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "100",
          "content": [],
          "template": []
        },
        {
          "name": "期刊JCR大类分区",
          "id": "",
          "hint": "输入分区",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "他引次数",
          "id": "",
          "hint": "注明SCI或SSCI或CSSCI",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        }
      ]
    ],
    "numberLimit": "15",
    "content": [],
    "template": [
      [
        {
          "name": "名称",
          "id": "",
          "hint": "输入名称",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "出版单位或刊物名称",
          "id": "",
          "hint": "输入单位或名称",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "期号",
          "id": "",
          "hint": "输入期号",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "起止页码",
          "id": "",
          "hint": "输入起止页码",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "出版或发布年度",
          "id": "",
          "hint": "输入出版或年度",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "被SCI或EI或SSCI或CSSCI收录",
          "id": "",
          "hint": "填写是否",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "期刊影响因子",
          "id": "",
          "hint": "输入影响因子",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "被ESI收录为热点论文情况",
          "id": "",
          "hint": "填写情况",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "100",
          "content": [],
          "template": []
        },
        {
          "name": "期刊JCR大类分区",
          "id": "",
          "hint": "输入分区",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "他引次数",
          "id": "",
          "hint": "注明SCI或SSCI或CSSCI",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        }
      ]
    ]
  },
  {
    "name": "科研工作",
    "id": "",
    "hint": "限10项，只填报主持项目或排名前5的国家项目或排名前3的省级项目",
    "required": false,
    "type": "title",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "",
    "id": "",
    "hint": "",
    "required": false,
    "type": "scientific-effort",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [
      [
        {
          "name": "项目名称",
          "id": "",
          "hint": "输入项目名称",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "项目性质及来源",
          "id": "",
          "hint": "输入项目性质及来源",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "100",
          "content": [],
          "template": []
        },
        {
          "name": "项目经费",
          "id": "",
          "hint": "输入项目经费",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "开始时间",
          "id": "",
          "hint": "",
          "required": false,
          "type": "date",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "",
          "content": [],
          "template": []
        },
        {
          "name": "结束时间",
          "id": "",
          "hint": "",
          "required": false,
          "type": "date",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "",
          "content": [],
          "template": []
        },
        {
          "name": "申报人在项目中的职位和任务",
          "id": "",
          "hint": "输入任务和职位",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "参与人数",
          "id": "",
          "hint": "输入参与人数",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        }
      ]
    ],
    "numberLimit": "10",
    "content": [],
    "template": [
      [
        {
          "name": "项目名称",
          "id": "",
          "hint": "输入项目名称",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "项目性质及来源",
          "id": "",
          "hint": "输入项目性质及来源",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "100",
          "content": [],
          "template": []
        },
        {
          "name": "项目经费",
          "id": "",
          "hint": "输入项目经费",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "开始时间",
          "id": "",
          "hint": "",
          "required": false,
          "type": "date",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "",
          "content": [],
          "template": []
        },
        {
          "name": "结束时间",
          "id": "",
          "hint": "",
          "required": false,
          "type": "date",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "",
          "content": [],
          "template": []
        },
        {
          "name": "申报人在项目中的职位和任务",
          "id": "",
          "hint": "输入任务和职位",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "参与人数",
          "id": "",
          "hint": "输入参与人数",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        }
      ]
    ]
  },
  {
    "name": "科研获奖",
    "id": "",
    "hint": "限10项",
    "required": false,
    "type": "title",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "",
    "id": "",
    "hint": "",
    "required": false,
    "type": "scientific-prize",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [
      [
        {
          "name": "获奖项目名称",
          "id": "",
          "hint": "输入名称",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "奖励名称",
          "id": "",
          "hint": "输入名称",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "奖励等级",
          "id": "",
          "hint": "输入名称",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "授奖国别或部门",
          "id": "",
          "hint": "输入名称",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "奖励年度",
          "id": "",
          "hint": "输入年度",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "排序",
          "id": "",
          "hint": "输入排序",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        }
      ]
    ],
    "numberLimit": "10",
    "content": [],
    "template": [
      [
        {
          "name": "获奖项目名称",
          "id": "",
          "hint": "输入名称",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "奖励名称",
          "id": "",
          "hint": "输入名称",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "奖励等级",
          "id": "",
          "hint": "输入名称",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "授奖国别或部门",
          "id": "",
          "hint": "输入名称",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "奖励年度",
          "id": "",
          "hint": "输入年度",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "排序",
          "id": "",
          "hint": "输入排序",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        }
      ]
    ]
  },
  {
    "name": "授权专利",
    "id": "",
    "hint": "限14项",
    "required": false,
    "type": "title",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "",
    "id": "",
    "hint": "",
    "required": false,
    "type": "patent-info",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [
      [
        {
          "name": "专利名称及专利号",
          "id": "",
          "hint": "输入名称及专利号",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "专利授权国或部门",
          "id": "",
          "hint": "输入授权国或部门",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "专利类别",
          "id": "",
          "hint": "输入专利类别",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "授权时间",
          "id": "",
          "hint": "",
          "required": false,
          "type": "date",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "",
          "content": [],
          "template": []
        },
        {
          "name": "专利保护期",
          "id": "",
          "hint": "输入专利保护期",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "本人排名",
          "id": "",
          "hint": "输入本人排名",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "专利所有者",
          "id": "",
          "hint": "输入专利所有者",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "所有专利权人",
          "id": "",
          "hint": "输入所有专利权人",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        }
      ]
    ],
    "numberLimit": "10",
    "content": [],
    "template": [
      [
        {
          "name": "专利名称及专利号",
          "id": "",
          "hint": "输入名称及专利号",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "专利授权国或部门",
          "id": "",
          "hint": "输入授权国或部门",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "专利类别",
          "id": "",
          "hint": "输入专利类别",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "授权时间",
          "id": "",
          "hint": "",
          "required": false,
          "type": "date",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "",
          "content": [],
          "template": []
        },
        {
          "name": "专利保护期",
          "id": "",
          "hint": "输入专利保护期",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "本人排名",
          "id": "",
          "hint": "输入本人排名",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "专利所有者",
          "id": "",
          "hint": "输入专利所有者",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "所有专利权人",
          "id": "",
          "hint": "输入所有专利权人",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        }
      ]
    ]
  },
  {
    "name": "附件验证",
    "id": "",
    "hint": "必填",
    "required": false,
    "type": "title",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "最高学位证书",
    "id": "",
    "hint": "最少1个，最多10个",
    "required": true,
    "type": "file-upload",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "10",
    "content": [],
    "template": []
  },
  {
    "name": "最高学历证书",
    "id": "",
    "hint": "最少1个，最多10个",
    "required": true,
    "type": "file-upload",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "10",
    "content": [],
    "template": []
  },
  {
    "name": "专业技术资格证",
    "id": "",
    "hint": "",
    "required": false,
    "type": "file-upload",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "10",
    "content": [],
    "template": []
  },
  {
    "name": "其他学历学位证书",
    "id": "",
    "hint": "",
    "required": false,
    "type": "file-upload",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "10",
    "content": [],
    "template": []
  },
  {
    "name": "科研项目证明",
    "id": "",
    "hint": "",
    "required": false,
    "type": "file-upload",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "10",
    "content": [],
    "template": []
  },
  {
    "name": "论文著作封面",
    "id": "",
    "hint": "",
    "required": false,
    "type": "file-upload",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "15",
    "content": [],
    "template": []
  },
  {
    "name": "专利证明",
    "id": "",
    "hint": "",
    "required": false,
    "type": "file-upload",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "10",
    "content": [],
    "template": []
  },
  {
    "name": "获奖证书",
    "id": "",
    "hint": "",
    "required": false,
    "type": "file-upload",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "10",
    "content": [],
    "template": []
  },
  {
    "name": "海外博士论文专家推荐信",
    "id": "",
    "hint": "",
    "required": false,
    "type": "file-upload",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "10",
    "content": [],
    "template": []
  },
  {
    "name": "其他类型附件",
    "id": "",
    "hint": "",
    "required": false,
    "type": "file-upload",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "10",
    "content": [],
    "template": []
  },
  {
    "name": "随迁配偶",
    "id": "",
    "hint": "如需随迁请填写",
    "required": false,
    "type": "title",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "配偶姓名",
    "id": "",
    "hint": "输入姓名",
    "required": false,
    "type": "text",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "50",
    "content": [],
    "template": []
  },
  {
    "name": "配偶出生日期",
    "id": "",
    "hint": "",
    "required": false,
    "type": "date",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "配偶学历",
    "id": "",
    "hint": "输入学历",
    "required": false,
    "type": "text",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "50",
    "content": [],
    "template": []
  },
  {
    "name": "配偶现工作单位",
    "id": "",
    "hint": "输入现工作单位",
    "required": false,
    "type": "text",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "50",
    "content": [],
    "template": []
  },
  {
    "name": "配偶职称",
    "id": "",
    "hint": "输入职称",
    "required": false,
    "type": "text",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "50",
    "content": [],
    "template": []
  },
  {
    "name": "子女信息",
    "id": "",
    "hint": "",
    "required": false,
    "type": "title",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "",
    "id": "",
    "hint": "",
    "required": false,
    "type": "childs-info",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [
      [
        {
          "name": "子女姓名",
          "id": "",
          "hint": "输入子女姓名",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "子女出生日期",
          "id": "",
          "hint": "",
          "required": false,
          "type": "date",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "",
          "content": [],
          "template": []
        },
        {
          "name": "子女性别",
          "id": "",
          "hint": "",
          "required": false,
          "type": "radio",
          "optionNum": "",
          "optionValue": [
            "男",
            "女"
          ],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "1",
          "content": [],
          "template": []
        },
        {
          "name": "子女在读学校",
          "id": "",
          "hint": "输入在读学校",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "子女年级",
          "id": "",
          "hint": "输入年级",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        }
      ]
    ],
    "numberLimit": "10",
    "content": [],
    "template": [
      [
        {
          "name": "子女姓名",
          "id": "",
          "hint": "输入子女姓名",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "子女出生日期",
          "id": "",
          "hint": "",
          "required": false,
          "type": "date",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "",
          "content": [],
          "template": []
        },
        {
          "name": "子女性别",
          "id": "",
          "hint": "",
          "required": false,
          "type": "radio",
          "optionNum": "",
          "optionValue": [
            "男",
            "女"
          ],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "1",
          "content": [],
          "template": []
        },
        {
          "name": "子女在读学校",
          "id": "",
          "hint": "输入在读学校",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        },
        {
          "name": "子女年级",
          "id": "",
          "hint": "输入年级",
          "required": false,
          "type": "text",
          "optionNum": "",
          "optionValue": [],
          "optionMoreNum": "",
          "optionMoreValue": [],
          "childComps": [],
          "numberLimit": "50",
          "content": [],
          "template": []
        }
      ]
    ]
  },
  {
    "name": "应聘信息",
    "id": "",
    "hint": "必填",
    "required": false,
    "type": "title",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "应聘单位",
    "id": "1",
    "hint": "",
    "required": true,
    "type": "radio",
    "optionNum": "27",
    "optionValue": [
      "工商管理学院",
      "公共管理学院(含廉政研究中心)",
      "新闻与传播学院",
      "美术与设计学院",
      "地理科学学院",
      "生命科学学院",
      "土木工程学院",
      "体育学院",
      "国际教育学院(含意大利研究中心)",
      "经济与统计学院",
      "教育学院(师范学院)",
      "外国语学院",
      "数学与信息科学学院",
      "计算机科学与教育软件学院(合署数学教育软件研究中心)",
      "化学化工学院",
      "建筑与城市规划学院",
      "马克思主义学院（政治与公民教育学院）",
      "教师培训学院继续教育学院",
      "法学院(律师学院)(含检察理论研究中心)",
      "人文学院(含十三行研究中心)",
      "音乐舞蹈学院",
      "物理与电子工程学院",
      "机械与电气工程学院",
      "环境科学与工程学院",
      "旅游学院(中法旅游学院)",
      "卫斯理安学院",
      "创新创业学院",
      "智能制造工程研究院",
      "智能软件技术研究院",
      "淡江大学工程结构灾害与控制联合研究中心",
      "工程抗震研究中心(含土木工程防护研究中心)",
      "广州发展研究院",
      "网络空间先进技术研究院"
    ],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "是否有境外居留证（绿卡）",
    "id": "",
    "hint": "",
    "required": false,
    "type": "radio",
    "optionNum": "2",
    "optionValue": ["是","否"],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "博后情况",
    "id": "",
    "hint": "",
    "required": false,
    "type": "text",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "50",
    "content": [],
    "template": []
  },
  {
    "name": "应届毕业生/在职调动",
    "id": "",
    "hint": "",
    "required": false,
    "type": "radio",
    "optionNum": "",
    "optionValue": ["应届毕业生","在职调动"],
    "optionMoreNum": "2",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "何年何月获得（或预计获得）博士学位",
    "id": "",
    "hint": "",
    "required": false,
    "type": "date",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "",
    "content": [],
    "template": []
  },
  {
    "name": "聘任专业技术级别",
    "id": "",
    "hint": "",
    "required": false,
    "type": "text",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "50",
    "content": [],
    "template": []
  },
  {
    "name": "导师类别",
    "id": "",
    "hint": "",
    "required": false,
    "type": "text",
    "optionNum": "",
    "optionValue": [],
    "optionMoreNum": "",
    "optionMoreValue": [],
    "childComps": [],
    "numberLimit": "50",
    "content": [],
    "template": []
  }
]

export const testMap = [
  {
    "id": 0,
    "name": "证件照",
    "type": "title"
  },
  {
    "id": 1,
    "name": "添加头像",
    "type": "picture-upload"
  },
  {
    "id": 2,
    "name": "基本信息",
    "type": "title"
  },
  {
    "id": 3,
    "name": "姓名",
    "type": "text"
  },
  {
    "id": 4,
    "name": "性别",
    "type": "radio"
  },
  {
    "id": 5,
    "name": "出生日期",
    "type": "date"
  },
  {
    "id": 6,
    "name": "国籍",
    "type": "radio"
  },
  {
    "id": 7,
    "name": "籍贯",
    "type": "text"
  },
  {
    "id": 8,
    "name": "身份证号或护照号",
    "type": "text"
  },
  {
    "id": 9,
    "name": "学术学历",
    "type": "title"
  },
  {
    "id": 10,
    "name": "专业",
    "type": "text"
  },
  {
    "id": 11,
    "name": "最高学位",
    "type": "text"
  },
  {
    "id": 12,
    "name": "最高学历",
    "type": "radio"
  },
  {
    "id": 13,
    "name": "人才称号",
    "type": "checkbox"
  },
  {
    "id": 14,
    "name": "职务",
    "type": "radio"
  },
  {
    "id": 15,
    "name": "职称",
    "type": "radio"
  },
  {
    "id": 16,
    "name": "学科领域",
    "type": "text"
  },
  {
    "id": 17,
    "name": "现工作单位",
    "type": "text"
  },
  {
    "id": 18,
    "name": "博士后单位",
    "type": "radio"
  },
  {
    "id": 19,
    "name": "联系方式",
    "type": "title"
  },
  {
    "id": 20,
    "name": "联系手机",
    "type": "text"
  },
  {
    "id": 21,
    "name": "电子邮箱",
    "type": "text"
  },
  {
    "id": 22,
    "name": "通讯地址",
    "type": "text"
  },
  {
    "id": 23,
    "name": "教育/工作经历",
    "type": "title"
  },
  {
    "id": 24,
    "name": "第一学历院校",
    "type": "text"
  },
  {
    "id": 25,
    "name": "最高学历院校",
    "type": "text"
  },
  {
    "id": 26,
    "name": "",
    "type": "experience"
  },
  {
    "id": 27,
    "name": "论文著作",
    "type": "title"
  },
  {
    "id": 28,
    "name": "",
    "type": "thesis-work"
  },
  {
    "id": 29,
    "name": "科研工作",
    "type": "title"
  },
  {
    "id": 30,
    "name": "",
    "type": "scientific-effort"
  },
  {
    "id": 31,
    "name": "科研获奖",
    "type": "title"
  },
  {
    "id": 32,
    "name": "",
    "type": "scientific-prize"
  },
  {
    "id": 33,
    "name": "授权专利",
    "type": "title"
  },
  {
    "id": 34,
    "name": "",
    "type": "patent-info"
  },
  {
    "id": 35,
    "name": "附件验证",
    "type": "title"
  },
  {
    "id": 36,
    "name": "最高学位证书",
    "type": "file-upload"
  },
  {
    "id": 37,
    "name": "最高学历证书",
    "type": "file-upload"
  },
  {
    "id": 38,
    "name": "专业技术资格证",
    "type": "file-upload"
  },
  {
    "id": 39,
    "name": "其他学历学位证书",
    "type": "file-upload"
  },
  {
    "id": 40,
    "name": "科研项目证明",
    "type": "file-upload"
  },
  {
    "id": 41,
    "name": "论文著作封面",
    "type": "file-upload"
  },
  {
    "id": 42,
    "name": "专利证明",
    "type": "file-upload"
  },
  {
    "id": 43,
    "name": "获奖证书",
    "type": "file-upload"
  },
  {
    "id": 44,
    "name": "海外博士论文专家推荐信",
    "type": "file-upload"
  },
  {
    "id": 45,
    "name": "其他类型附件",
    "type": "file-upload"
  },
  {
    "id": 46,
    "name": "随迁配偶",
    "type": "title"
  },
  {
    "id": 47,
    "name": "配偶姓名",
    "type": "text"
  },
  {
    "id": 48,
    "name": "配偶出生日期",
    "type": "date"
  },
  {
    "id": 49,
    "name": "配偶学历",
    "type": "text"
  },
  {
    "id": 50,
    "name": "配偶现工作单位",
    "type": "text"
  },
  {
    "id": 51,
    "name": "配偶职称",
    "type": "text"
  },
  {
    "id": 52,
    "name": "子女信息",
    "type": "title"
  },
  {
    "id": 53,
    "name": "",
    "type": "childs-info"
  },
  {
    "id": 54,
    "name": "应聘信息",
    "type": "title"
  },
  {
    "id": 55,
    "name": "应聘单位",
    "type": "radio"
  },
  {
    "id": 56,
    "name": "是否有境外居留证（绿卡）",
    "type": "radio"
  },
  {
    "id": 57,
    "name": "博后情况",
    "type": "text"
  },
  {
    "id": 58,
    "name": "应届毕业生/在职调动",
    "type": "radio"
  },
  {
    "id": 59,
    "name": "何年何月获得（或预计获得）博士学位",
    "type": "date"
  },
  {
    "id": 60,
    "name": "聘任专业技术级别",
    "type": "text"
  },
  {
    "id": 61,
    "name": "导师类别",
    "type": "text"
  }
]

export const testHrdData = [
  {
    "Openid": "1",
    "IsPass": true,
    "HundredInfo": {
      "TIndex": "123",
      "Department": "123",
      "Name": "揭啸宇",
      "Nationality": "123",
      "Sex": "123",
      "Birthday": "123",
      "FirstDegree": "123",
      "TopDegree": "123",
      "Degree": "123",
      "Profession": "123",
      "Workplace": "123",
      "Position": "123",
      "PositionalTitle": "123",
      "TalentKind": "123",
      "Thesis": "123",
      "Science": "123",
      "Contact": "123",
      "EMail": "123",
      "PositionKind": "123",
      "Salary": "123",
      "ScienceMoney": "123",
      "HouseMoney": "123",
      "HirePosition": "123",
      "HireTime": "123",
      "MetorKind": "123",
      "TechLevel": "123",
      "Tips": "123",
      "ID": "789"
    }
  },
  {
    "Openid": "1",
    "HundredInfo": {
      "TIndex": "123",
      "Department": "123",
      "Name": "123",
      "Nationality": "123",
      "Sex": "123",
      "Birthday": "123",
      "FirstDegree": "123",
      "TopDegree": "123",
      "Degree": "123",
      "Profession": "123",
      "Workplace": "123",
      "Position": "123",
      "PositionalTitle": "123",
      "TalentKind": "123",
      "Thesis": "123",
      "Science": "123",
      "Contact": "123",
      "EMail": "123",
      "PositionKind": "123",
      "Salary": "123",
      "ScienceMoney": "123",
      "HouseMoney": "123",
      "HirePosition": "123",
      "HireTime": "123",
      "MetorKind": "123",
      "TechLevel": "123",
      "Tips": "123",
      "ID": "789"
    },
    "IsPass": true
  },
  {
    "Openid": "1",
    "HundredInfo": {
      "TIndex": "123",
      "Department": "123",
      "Name": "123",
      "Nationality": "123",
      "Sex": "123",
      "Birthday": "123",
      "FirstDegree": "123",
      "TopDegree": "123",
      "Degree": "123",
      "Profession": "123",
      "Workplace": "123",
      "Position": "123",
      "PositionalTitle": "123",
      "TalentKind": "123",
      "Thesis": "123",
      "Science": "123",
      "Contact": "123",
      "EMail": "123",
      "PositionKind": "123",
      "Salary": "123",
      "ScienceMoney": "123",
      "HouseMoney": "123",
      "HirePosition": "123",
      "HireTime": "123",
      "MetorKind": "123",
      "TechLevel": "123",
      "Tips": "123",
      "ID": "789"
    },
    "IsPass": true
  }
]

export const testLecData = [
  {
      "Openid": "1",
      "NewLectureInfo": {
          "TIndex": "123",
          "Department": "123",
          "Name": "123",
          "Nationality": "123",
          "Sex": "123",
          "Birthday": "123",
          "Id": "123",
          "FirstDegree": "123",
          "TopDegree": "123",
          "Degree": "123",
          "Profession": "123",
          "Workplace": "123",
          "Position": "123",
          "Thesis": "123",
          "Science": "123",
          "Email": "123",
          "Allowance": "123",
          "OtherRequire": "123"
      },
      "IsPass": true
  },
  {
      "Openid": "1",
      "NewLectureInfo": {
          "TIndex": "123",
          "Department": "123",
          "Name": "123",
          "Nationality": "123",
          "Sex": "123",
          "Birthday": "123",
          "Id": "123",
          "FirstDegree": "123",
          "TopDegree": "123",
          "Degree": "123",
          "Profession": "123",
          "Workplace": "123",
          "Position": "123",
          "Thesis": "123",
          "Science": "123",
          "Email": "123",
          "Allowance": "123",
          "OtherRequire": "123"
      },
      "IsPass": true
  },
  {
      "Openid": "1",
      "NewLectureInfo": {
          "TIndex": "123",
          "Department": "123",
          "Name": "123",
          "Nationality": "123",
          "Sex": "123",
          "Birthday": "123",
          "Id": "123",
          "FirstDegree": "123",
          "TopDegree": "123",
          "Degree": "123",
          "Profession": "123",
          "Workplace": "123",
          "Position": "123",
          "Thesis": "123",
          "Science": "123",
          "Email": "123",
          "Allowance": "123",
          "OtherRequire": "123"
      },
      "IsPass": true
  }
]

export const testCheck = {
  "name": "大叔控",
  "alcoid": "1507400061",
  "job": "领军人才",
  "pcstype": "百人计划",
  "employer": "计算机科学与教育软件学院(合署数学教育软件研究中心)",
  "curpcsid": 9,
  "actions": [
    {
      "type": "button",
      "name": "审核",
      "icon": "check"
    }
  ]
}